npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "589BDB6D-0B22-4C64-BEE2-8E897F8BC7A0"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "589BDB6D-0B22-4C64-BEE2-8E897F8BC7A0"